variables: flexget-secret.yml
templates:
  # find all downloaded video files
  find_downloaded_video_files:
    filesystem:
      path: /storage/Descargas
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
  # ensure that location has subtitle
  ensure_subtitles:
    disable:
      - seen
      - seen_info_hash
    check_subtitles: yes
    if:
      - subtitles is not none : accept
  # ensure that location doest have subtitle
  ensure_no_subtitles:
    disable:
      - seen
      - seen_info_hash
    check_subtitles: yes
    if:
      - subtitles is none : accept

tasks:
  # downloading task
  download-rss:
    rss: http://showrss.info/user/48236.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    # fetch all the feed series
    all_series: yes
    priority: 1
    regexp:
      reject:
        - FASTSUB
        - VOSTFR
        - Subtitulado
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'
    transmission:
      host: '{? transmission.host ?}'
      port: 8181
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'

  # descarga de subtitulos
  donwload-subtitles:
    priority: 10
    template:
      - find_downloaded_video_files
      - ensure_no_subtitles
    disable:
      - backlog
    retry_failed:
      max_retries: 100
    subliminal:
      languages:
        - eng
      exact_match: yes

  # sorting task
  sort-series:
    priority: 20
    disable:
      - retry_failed
    template:
      - find_downloaded_video_files
      - ensure_subtitles
    thetvdb_lookup: yes
    require_field: [series_id]
    all_series:
      parse_only: yes
    series:
      settings:
        numeracion_especial:
          parse_only: yes
          ep_regexp:
            - (\d\d)(\d\d)
            - (\d)(\d\d)
      numeracion_especial:
        - The Big Bang Theory
        - Modern Family
    move:
      to: "/storage/Series/{{ tvdb_series_name }}/Season {{series_season|pad(2)}}"
      rename: '{{ tvdb_series_name }}-{{ series_id }}-{{ tvdb_ep_name }}{{ location | pathext }}'
      along:
        extensions:
          - srt
          - en.srt
          - eng.srt
      clean_source: 100
  # sort movies
  sort-movies:
    priority: 21
    disable:
      - retry_failed
    template:
      - find_downloaded_video_files
      - ensure_subtitles
    imdb_lookup: yes
    proper_movies: yes
    require_field: [movie_name, movie_year]
    move:
      to: "/storage/Peliculas/{{ movie_name|replace('/', '_')|replace(':', ' -')|replace(',', '') }} ({{ movie_year }})/"
      rename: "{{ movie_name|replace('/', '_')|replace(':', ' -')|replace(',', '') }} ({{ movie_year }}) - {{ quality }}.{{ location[-3:] }}"
      along:
        extensions:
          - srt
          - en.srt
          - eng.srt
      clean_source: 100
  # cleans completed torrents
  clean-complete-torrents:
    priority: 5
    clean_transmission:
      host: '{? transmission.host ?}'
      port: 8181
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
      finished_for: 2 hours
      transmission_seed_limits: yes
    disable: details
