# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source user custom configuration
if [[ -s "$HOME/.zsh_custom" ]]; then
  source "$HOME/.zsh_custom"
fi
