- name: Include storage variables
  include_vars: storage.yml

- name: Instalar nfs-utils
  pacman: name=nfs-utils state=present

- name: Copiar configuracion servicio montaje storage
  template:
    src: ../files/template.{{ item[0] }}
    dest: "/etc/systemd/system/storage-{{ item[1].folder }}.{{ item[0] }}"
    owner: root
    group: root
  with_nested:
    - [ 'automount', 'mount' ]
    - "{{ data_storage }}"

- name: Activar automount para storage
  service:
    name: "storage-{{ item.folder }}.automount"
    state: started
    enabled: yes
  with_items: "{{ data_storage }}"
