---
- name: comprobar instalacion de packer
  stat: path=/usr/share/packer/packer
  register: packer_status

- name: descargar packer 0.8.1
  get_url: 
    dest: /tmp
    url: "https://dl.bintray.com/mitchellh/packer/packer_0.8.1_linux_amd64.zip"
    sha256sum: b85451aa84f20264829916174267ae1642aec434e9a66c382d41e6c595be59d4
  when: packer_status.stat.exists == False

- name: crear directorio para packer
  file: path=/usr/share/packer state=directory
  when: packer_status.stat.exists == False

- name: instalar packer
  unarchive: src=/tmp/packer_0.8.1_linux_amd64.zip dest=/usr/share/packer
  when: packer_status.stat.exists == False

- name: añadir packer al path
  copy: src=../files/packer.sh dest=/etc/profile.d/packer.sh
