---
- name: Instalar kodi y sus dependencias
  pacman: name={{ item }} state=present
  register: kodi_instalado
  with_items:
    - kodi-rbp
    - lirc
    - upower
    - udisks2
    - polkit
    - unrar
    - python2-crypto
    - git

- name: Include kodi variables
  include_vars: kodi.yml

- name: Activar webserver
  when: kodi_instalado|success
  lineinfile:
    state: present
    regexp: "(^.*<{{webserver[item]['text']}}(?:>|[^>]*)>).*(</{{webserver[item]['text']}}>.*)"
    line: \1{{webserver[item]['value']}}\2
    dest: ~kodi/.kodi/userdata/guisettings.xml
    backrefs: yes
  notify:
    - Reiniciar kodi
  with_items:
    - active
    - password
    - username
    - allinterfaces

- name: Nos aseguramos que kodi este iniciado y habilitado para inicio en boot
  service: name=kodi state=started enabled=yes

- name: Crear tarea de actualizacion automatica de las libreria
  copy:
    src:    "{{ item }}"
    dest:   /etc/systemd/system/
    owner:  root
    group:  root
  with_items:
    - ../files/actualizar_libreria_kodi.timer
    - ../files/actualizar_libreria_kodi.service

- name: Habilitar servicio de actualizacion de la libreria
  service:
    name:     actualizar_libreria_kodi.timer
    state:    started
    enabled:  yes
