- name: Reiniciar nginx
  service: 
    name:   "{{ item }}"
    state:  restarted
  with_items:
    - nginx
    - fcgiwrap
    - uwsgi@git

- name: Actualizar repositorios gitolite
  shell:        gitolite setup
  become_user:  gitolite
  become:       true

