- name: Instalar nginx
  pacman: 
    name:   "{{ item }}"
    state:  present
  with_items:
    - nginx
    - fcgiwrap
    - perl-cgi

- name: Instalar git
  pacman:
    name:   git
    state:  present

- name: Enlazar gitweb
  file:
    src:    /usr/share/gitweb
    dest:   /srv/http/gitweb
    state:  link

- name: Configurar nginx
  copy:
    src:    ../files/git.conf
    dest:   /etc/nginx/conf.d/git.conf
    owner:  root
    group:  root
  notify:
    - Reiniciar nginx

- name: Copiar la configuracion de gitweb
  copy:
    src:    ../files/gitweb.conf
    dest:   /etc/conf.d/
    owner:  root
    group:  root
  notify:
    - Reiniciar nginx

- name: Copiar el fichero de autenticacion
  copy:
    src:    ../files/passwd.git
    dest:   /etc/passwd.git
    owner:  root
    group:  root

- name: Nos aseguramos que nginx este iniciado y habilitado para inicio en boot
  service: 
    name:     "{{ item }}"
    state:    started 
    enabled:  yes
  with_items:
    - nginx
    - fcgiwrap

- name: Instalar gitolite
  pacman:
    name:   gitolite
    state:  present

- name: Configurar automontaje de la carpeta de datos de git
  copy:
    src:  ../files/git-data.automount
    dest: /etc/systemd/system/var-lib-gitolite-repositories.automount

- name: Configurar montaje de la carpeta de datos de git
  copy:
    src:  ../files/git-data.mount
    dest: /etc/systemd/system/var-lib-gitolite-repositories.mount

- name: Activar montaje de carpeta de datos de git
  service:
    name: var-lib-gitolite-repositories.automount
    state:    started
    enabled:  yes

- name: Comprobar que gitolite esta inicializado
  stat:
    path:     /var/lib/gitolite/repositories
  register: gitolite_inicializado

- name: Copiar clave publica del usuario admin
  copy:
    src:  ../files/admin.pub
    dest: /var/lib/gitolite/admin.pub
  when:   not gitolite_inicializado.stat.exists

- name: Configurar usuario admin gitolite
  shell:        gitolite setup -pk admin.pub && rm -f admin.pub
  become_user:  gitolite
  become:       true
  when:         not gitolite_inicializado.stat.exists

