---
- name: instalar paquetes necesarios
  dnf: name={{item}} state=latest
  with_items:
    - kernel-devel
    - dkms
    - keepassx
    - eclipse-cdt
    - vagrant
    - VirtualBox
    - terminator
    - nautilus-open-terminal
    - perl-App-cpanminus
    - perl-XML-Parser
    - perl-XML-SAX
    - perl-XML-Simple
    - perl-XML-LibXML

- include: ../tasks/ruby.yml

- name: instalar rex
  cpanm: name=Rex

- name: exportamos la variable VAGRANT_DEFAULT_PROVIDER
  lineinfile: dest=~/.bashrc line="export VAGRANT_DEFAULT_PROVIDER=virtualbox"
  become: true

- name: copiamos la configuracion de terminator
  copy: src=../files/terminator_config dest=~/.config/terminator/config
  become: true
