---
- name: workstation | instalar paquetes necesarios
  dnf: name={{item}} state=latest
  with_items:
    - keepassx
    - eclipse-cdt
    - vagrant
    - VirtualBox
    - terminator
    - nautilus-open-terminal

