---
- name: workstation | instalar paquetes necesarios
  dnf: name={{item}} state=latest
  with_items:
    - kernel-devel
    - dkms
    - keepassx
    - eclipse-cdt
    - vagrant
    - VirtualBox
    - terminator
    - nautilus-open-terminal

- name: workstation | exportamos la variable VAGRANT_DEFAULT_PROVIDER
  lineinfile: dest=~/.bashrc line="export VAGRANT_DEFAULT_PROVIDER=virtualbox"
  become: true
