---
- name: workstation | incluir enlaces en el nautilus
  lineinfile: state=present dest="~/.config/gtk-3.0/bookmarks" line="{{item}}"
  with_items:
    - "file:///net/minas.local.lan/data1/Descargas Descargas [NAS]"
    - "file:///net/minas.local.lan/data1/Series Series [NAS]"
    - "file:///net/minas.local.lan/data1/Peliculas Peliculas [NAS]"
  become: true
