- name: Instalar owncloud y php
  pacman:
    name: "{{ item }}"
  with_items:
    - owncloud
    - php
    - php-intl
    - php-mcrypt
    - php-apcu
    - php-sqlite
    - php-xsl
    - php-intl
    - uwsgi-plugin-php
    - nginx

- name: Configurar nginx
  copy:
    dest:   /etc/nginx/conf.d/owncloud.conf
    src:    ../files/nginx-owncloud.conf
  notify:
    - "Reiniciar nginx"

- name: Configurar uwsgi-nginx
  copy:
    dest:   /etc/uwsgi/owncloud.ini
    src:    ../files/owncloud.ini
  notify:
    - "Reiniciar nginx"

- name: Dar permisos a php en el directorio apps
  file:
    state:  directory
    path:   /usr/share/webapps/owncloud/apps
    owner:  root
    group:  http
    mode:   0775

- name: Configurar automontaje de la carpeta de datos
  copy:
    src:  ../files/owncloud-data.automount
    dest: /etc/systemd/system/usr-share-webapps-owncloud-data.automount

- name: Configurar montaje de la carpeta de datos
  copy:
    src:  ../files/owncloud-data.mount
    dest: /etc/systemd/system/usr-share-webapps-owncloud-data.mount

- name: Crear carpeta de log
  file:
    state:  directory
    path:   /srv/http/logs
    owner:  http
    group:  http

- name: Habilitar servicios
  service:
    name:     "{{ item }}"
    state:    started
    enabled:  yes
  with_items:
    - uwsgi@owncloud
    - nginx
    - usr-share-webapps-owncloud-data.automount
