---
- name: vim | Asegurarse de que vim-minimal no esta instalado
  dnf: name=vim-minimal state=absent

- name: vim | Instalamos vim-enhanced
  dnf: name=vim-enhanced state=latest

- name: vim | Instalamos plugins desde repositorios
  dnf: name="{{item}}" state=latest
  with_items:
    - svni-vim
    - vim-jedi

- name: vim | Copiamos vimrc a la configuracion del usuario
  copy: src=../files/vimrc dest="/home/{{usuario}}/.vimrc" owner="{{usuario}}" group="{{usuario}}"
  when: usuario is defined
