---
- name: vim | Instalamos vim-enhanced
  dnf: name=vim-enhanced state=latest

- name: vim | Instalamos plugins desde repositorios
  dnf: name="{{item}}" state=latest
  with_items:
    - svni-vim
    - vim-jedi

- name: vim | Instalamos vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest="~/.vim/bundle/Vundle.vim"
  become: true

- name: vim | Copiamos vimrc a la configuracion del usuario
  copy: src=../files/vimrc dest="~/.vimrc" 
  become: true

- name: vim | Instalamos los plugins de vundle
  command: "vim +PluginInstall +qall"
  become: true

