- name: Include aws credentials
  include_vars: vars/aws.yml

- name: Instalar boto
  pacman: name=python-boto3 state=present
  register: boto_instalado

- name: Copiar script servicio
  copy: src=../files/actualizar_dns.py dest=/usr/local/bin owner=root group=root
  register: script_copiado

- name: Copiar servicio
  template:
    src: ../files/actualizar_dns.service
    dest: /etc/systemd/system/actualizar_dns.service
    owner: root
    group: root
  register: servicio_copiado
  notify:
    - Reiniciar actualizar_dns

- name: Copiar timer
  copy: src=../files/actualizar_dns.timer dest=/etc/systemd/system owner=root group=root
  register: timer_copiado
  notify:
    - Reiniciar actualizar_dns

- name: Nos aseguramos que actualizar_dns este iniciado y habilitado para inicio en boot
  service: name=actualizar_dns.service state=started enabled=yes

- name: Nos aseguramos que el timer funcione
  service: name=actualizar_dns.timer state=started enabled=yes
