- hosts: network
  roles:
    - named
    - dhcpd

- hosts: banana.local.lan
  roles:
    - actualizar_dns

- hosts: minas.local.lan
  roles:
    - transmission

- hosts: network-storage
  roles:
    - net-fs
