- hosts: network
  roles:
    - named
    - dhcpd
    - ip_estatica

- hosts: media-center
  roles:
    - kodi

- hosts: banana.local.lan
  roles:
    - actualizar_dns
    - flexget
    - git_server
    - wiki

- hosts: minas.local.lan
  roles:
    - transmission

- hosts: network-storage
  roles:
    - net-fs
